namespace NZWalks.API.Models.DTO
{
    public class AddRegionRequest
    {
        // very similar to region, but no access to ID since that is generated by the app

        public string Code { get; set; }
        public string Name { get; set; }
        public double Area { get; set; }
        public double Lat { get; set; }
        public double Long { get; set; }
        public long Population { get; set; }
    }
}
