namespace NZWalks.API.Models.DTO
{
    public class UpdateRegionRequest
    {

        // very similar to region, but no access to ID since that is generated by the app
        // client will be able to update these fields 

        public string Code { get; set; }
        public string Name { get; set; }
        public double Area { get; set; }
        public double Lat { get; set; }
        public double Long { get; set; }
        public long Population { get; set; }
    }
}
